name: AWS SSM Parameter Workflow

on:
    push:
        branches:
        - main

env:
    TF_LOG: INFO
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    AWS_REGION: ap-south-1

jobs:
    store-ssm-parameter:
        runs-on: ubuntu-latest

        environment: nadcm

        steps:
        - name: Install AWS CLI
          run: sudo snap install aws-cli --classic
        
        - name: Push Slack WebHook URL To SSM Parameter
          id: slack-webhook
          run: |
               aws ssm put-parameter --name /nadcm/slack/webhook_url --type "String" --value ${{ secrets.WEBHOOK_URL }} --overwrite
        
        - name: Push Spark API Key To SSM Parameter
          id: slack-api-key
          run: |
               aws ssm put-parameter --name /nadcm/spark/api_key --type "String" --value ${{ secrets.API_KEY }} --overwrite
        
        - name: Push Spark URL To SSM Parameter
          id: slack-url
          run: |
               aws ssm put-parameter --name /nadcm/spark/url --type "String" --value ${{ secrets.SPARK_URL }} --overwrite
    
    terraform-deployment:
        name: "Terraform Infrastructure Deployment"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        
        steps:
        - name: Checkout the repository
          uses: actions/checkout@v2
        
        - name: Setup Terraform with specified version
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.9.5
        
        - name: Terraform Init
          id: initialize
          run: terraform init
        
        - name: Terraform Apply
          id: apply resources
          run: terraform apply --auto-approve --input=false