name: AWS SSM Parameter Workflow

on:
    push:
        branches:
        - main

env:
    TF_LOG: INFO
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
    store-ssm-parameter:
        runs-on: ubuntu-latest

        steps:
        - name: Install AWS CLI
          run: sudo snap install aws-cli --classic
          